language: go

go:
  - 1.7

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  - go test ./...

after_success:
  - gox -output "build/{{.OS}}_{{.Arch}}_{{.Dir}}"
  - ghr --username Swatto --token $GITHUB_TOKEN --replace --prerelease --debug pre-release build/

notifications:
  email: false