language: go
go: 1.10.2
before_install:
  - go get github.com/magefile/mage
  - mage getvgo
#  - go get github.com/tcnksm/ghr

script:
  - mage test ./...

after_success:
  - mage all
#  - ghr --username deild --token $GITHUB_TOKEN --replace --prerelease --debug pre-release build/

notifications:
  email: false
