language: go
go: 1.10.x
before_install:
  - go get -u github.com/magefile/mage
  - mage getvgo
install: mage install
script:
  - mage test
  - mage all
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL http://git.io/goreleaser | bash
  #  - ghr --username deild --token $GITHUB_TOKEN --replace --prerelease --debug pre-release build/
notifications:
  email: false
